Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/VariableName:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/support/*'
