Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/VariableNumber:
  EnforcedStyle: snake_case
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
