development:
  secret_key_base: a2b7ffda297bb4c77fa14cbf5822b05c933d20f459f30de97d6dd4c9afbb7aaaea1f1ecd011d78c880ba722e4f47eda4d057adc0dbb0953bfdb721fd7187cdca
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>

test:
  secret_key_base: 0225648212ad7b891368cfb0163ee22c968aaa713a1b732b4ac4ed892b3e78812145f9f39d5ee9b97ddbe6cb70347c286300f2eae4c0752caf0232d2a52dda8a
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>
